### ISSUE TITLE
Suport for meta knight kirby strings?

### ISSUE THREAD

**Issue by mdavis40** [Ellisande/kirby#1]
It would be fantastic if Meta Knight Kirbies were supported. What are the chances of support being built in to your next release?

I'm not a developer otherwise I'd submit a pull request.

**Comment by rob-miller-777** [comment]
I have also been hoping for this feature for a long time.  I think it would be a great enhancement to this product suite.

**Comment by danacblack** [comment]
Or possibly the 2017 Kirby? `༼ つ ◕_◕ ༽つ`

**Comment by Ellisande** [comment]
@mdskd You have the ascii for a meta knight?

**Comment by Ellisande** [comment]
@danacblack please open a separate issue for 2017 Kirby as its off topic

**Comment by mdavis40** [comment]
@Ellisande yessir, I am uncertain if this is the widely accepted meta knight ascii:

`<(*^*)>`

**Comment by Ellisande** [comment]
Fixed https://github.com/Ellisande/kirby/blob/master/test/test.js#L54
