### ISSUE TITLE
Support for 2017 Kirby

### ISSUE THREAD

**Issue by danacblack** [Ellisande/kirby#2]
This string is even less common and would be more useful:  `༼ つ ◕_◕ ༽つ`

**Comment by Ellisande** [comment]
Fixed https://github.com/Ellisande/kirby/blob/master/test/test.js#L105

**Comment by chpio** [comment]
wow, nice enhancement, thank you for your contribution

**Comment by chpio** [comment]
i think it should be documented in the README
